name: coronaPL gov PL data refresh
on:
  schedule:
    - cron:  '30 10,19 * * *'
jobs:
  data_refresh_master:
    name: dataset refresh
    runs-on: ubuntu-18.04
    steps:
      - name: checkout_repo
        uses: actions/checkout@v2
        with:
          ref: 'main'
      - name: Refresh the data
        run: python ./gov/govData.py
